#!/bin/bash

# Update agent context with latest project information

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

PROJECT_ROOT=$(get_project_root)
MEMORY_DIR="$PROJECT_ROOT/.specify/memory"
CONTEXT_FILE="$MEMORY_DIR/agent-context.md"

ensure_dir "$MEMORY_DIR"

print_info "Updating agent context..."

# Gather project information
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
LAST_UPDATE=$(get_timestamp)

# Create or update context file
cat > "$CONTEXT_FILE" <<EOF
# Agent Context

Last Updated: ${LAST_UPDATE}

## Project Information

- **Repository**: $(basename "$PROJECT_ROOT")
- **Current Branch**: ${GIT_BRANCH}
- **Latest Commit**: ${GIT_COMMIT}

## Recent Activity

$(git log --oneline -5 2>/dev/null || echo "No git history available")

## Project Structure

\`\`\`
$(tree -L 2 -I 'node_modules|.git' "$PROJECT_ROOT" 2>/dev/null || find "$PROJECT_ROOT" -maxdepth 2 -type d | head -20)
\`\`\`

## Active Specifications

$(find "$PROJECT_ROOT/.specify/specs" -name "*.md" 2>/dev/null | xargs basename -s .md 2>/dev/null || echo "No specifications found")

## Active Plans

$(find "$PROJECT_ROOT/.specify/plans" -name "*.md" 2>/dev/null | xargs basename -s .md 2>/dev/null || echo "No plans found")

## Next Steps

<!-- Update this section with current priorities -->

---
Auto-generated by update-agent-context.sh
EOF

print_success "Agent context updated: $CONTEXT_FILE"
